k_values: [2, 3, 4, 5, 7, 9, 11, 13, 15, 18, 21, 24, 27, 30]

input_start: "Results_anonymisation/Gen_Anony_"

pre_input: "Pre_processing/Gen_Anony_"

method: "general"

transform: True

learning_rate: 0.1

nearest_neighbors: 5

dataset: "car"

target: "class"